create table Unicorns (
	Id				int				not null,
	name			varchar (100)	not null,
	birthday		date			not null,
	color			int				not null,
	description 	varchar (1000)	not null,
	primary key clustered (Id asc)
);

create table SpecialUnicornAbilities (
	unicornId				int		not null,
	specialAbilitiesId		int		not null
	primary key (unicornId, specialAbilitiesId),
	foreign key (unicornId) 			references Unicorns (Id),
	foreign key (specialAbilitiesId)	references SpecialAbilities (Id)
);

create table SpecialAbilities (
	Id				int				not null,
	name			varchar (100)	not null,
	description		varchar (1000)	not null,
	primary key clustered (Id asc)
);

insert into Unicorn (id, name, birthday, color, description) values (1, 'Pseudalopex gymnocercus', '3/17/0359', 805137, 'Suspendisse impotenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into Unicorn (id, name, birthday, color, description) values (2, 'Fratercula corniculata', '9/21/1230', 7559408, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.');
insert into Unicorn (id, name, birthday, color, description) values (3, 'Haliaetus leucogaster', '10/3/1235', 2170496, 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus.');
insert into Unicorn (id, name, birthday, color, description) values (4, 'Tadorna tadorna', '8/28/1596', 3065052, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into Unicorn (id, name, birthday, color, description) values (5, 'Ammospermophilus nelsoni', '5/5/0051', 9871741, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into Unicorn (id, name, birthday, color, description) values (6, 'Semnopithecus entellus', '6/29/0671', 16416769, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into Unicorn (id, name, birthday, color, description) values (7, 'Philetairus socius', '4/8/1308', 5576546, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into Unicorn (id, name, birthday, color, description) values (8, 'Choriotis kori', '6/27/1550', 11645460, 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into Unicorn (id, name, birthday, color, description) values (9, 'Ctenophorus ornatus', '1/18/1629', 268009, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into Unicorn (id, name, birthday, color, description) values (10, 'Acanthaster planci', '5/18/0980', 2377717, 'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into Unicorn (id, name, birthday, color, description) values (11, 'Priodontes maximus', '6/21/0811', 7205033, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into Unicorn (id, name, birthday, color, description) values (12, 'Tadorna tadorna', '2/25/0758', 15238022, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl.');
insert into Unicorn (id, name, birthday, color, description) values (13, 'Gymnorhina tibicen', '11/4/1878', 15136473, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into Unicorn (id, name, birthday, color, description) values (14, 'Spizaetus coronatus', '9/29/1371', 10733369, 'Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into Unicorn (id, name, birthday, color, description) values (15, 'Spizaetus coronatus', '5/12/1496', 3275912, 'In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into Unicorn (id, name, birthday, color, description) values (16, 'Marmota flaviventris', '11/29/0221', 12319014, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into Unicorn (id, name, birthday, color, description) values (17, 'Leptoptilus dubius', '8/13/1443', 6669536, 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.');
insert into Unicorn (id, name, birthday, color, description) values (18, 'Pitangus sulphuratus', '11/15/0509', 9641349, 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.');
insert into Unicorn (id, name, birthday, color, description) values (19, 'Bubo sp.', '9/30/1158', 7113545, 'Pellentesque eget nunc.');
insert into Unicorn (id, name, birthday, color, description) values (20, 'Cebus apella', '6/18/1704', 6955893, 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.');
insert into Unicorn (id, name, birthday, color, description) values (21, 'Coluber constrictor', '9/3/1709', 5484614, 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis. Donec semper sapien a libero.');
insert into Unicorn (id, name, birthday, color, description) values (22, 'Chelodina longicollis', '12/20/0653', 12778218, 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into Unicorn (id, name, birthday, color, description) values (23, 'Crotalus cerastes', '2/25/1635', 6804322, 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into Unicorn (id, name, birthday, color, description) values (24, 'Varanus sp.', '11/3/0085', 4990771, 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into Unicorn (id, name, birthday, color, description) values (25, 'Naja nivea', '7/15/1054', 13979650, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into Unicorn (id, name, birthday, color, description) values (26, 'Crocuta crocuta', '1/22/0429', 15939168, 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into Unicorn (id, name, birthday, color, description) values (27, 'Ciconia episcopus', '8/2/0451', 8360442, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Unicorn (id, name, birthday, color, description) values (28, 'Bubalus arnee', '3/30/2011', 1106525, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into Unicorn (id, name, birthday, color, description) values (29, 'Phalacrocorax carbo', '6/2/0041', 9273580, 'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into Unicorn (id, name, birthday, color, description) values (30, 'Damaliscus lunatus', '10/16/0471', 3200334, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into Unicorn (id, name, birthday, color, description) values (31, 'Pteropus rufus', '5/16/1733', 11901201, 'Vivamus tortor. Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into Unicorn (id, name, birthday, color, description) values (32, 'Zenaida galapagoensis', '5/17/0455', 14151596, 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into Unicorn (id, name, birthday, color, description) values (33, 'Morelia spilotes variegata', '6/28/0045', 9243059, 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into Unicorn (id, name, birthday, color, description) values (34, 'Phoenicopterus ruber', '8/7/0302', 10860123, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus. In sagittis dui vel nisl.');
insert into Unicorn (id, name, birthday, color, description) values (35, 'Canis aureus', '11/21/0812', 4391535, 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into Unicorn (id, name, birthday, color, description) values (36, 'Pycnonotus barbatus', '4/3/1730', 5036577, 'Donec ut mauris eget massa tempor convallis.');
insert into Unicorn (id, name, birthday, color, description) values (37, 'Lemur fulvus', '4/11/0876', 14441139, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.');
insert into Unicorn (id, name, birthday, color, description) values (38, 'Crotalus adamanteus', '8/7/0663', 7644161, 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est. Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into Unicorn (id, name, birthday, color, description) values (39, 'Corvus albus', '4/29/1365', 100328, 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into Unicorn (id, name, birthday, color, description) values (40, 'Pelecanus conspicillatus', '11/22/0631', 16730160, 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into Unicorn (id, name, birthday, color, description) values (41, 'Vicugna vicugna', '9/14/0372', 2225621, 'Sed ante. Vivamus tortor.');
insert into Unicorn (id, name, birthday, color, description) values (42, 'Felis caracal', '10/30/1081', 14726432, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum. Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into Unicorn (id, name, birthday, color, description) values (43, 'Macropus fuliginosus', '5/30/0341', 4138312, 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.');
insert into Unicorn (id, name, birthday, color, description) values (44, 'Gyps bengalensis', '8/12/0437', 9770875, 'Nulla tellus. In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.');
insert into Unicorn (id, name, birthday, color, description) values (45, 'Larus fuliginosus', '4/30/0483', 12358197, 'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into Unicorn (id, name, birthday, color, description) values (46, 'Phalaropus fulicarius', '7/20/0056', 13964885, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue.');
insert into Unicorn (id, name, birthday, color, description) values (47, 'Pycnonotus nigricans', '10/4/1842', 10964087, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into Unicorn (id, name, birthday, color, description) values (48, 'Phalacrocorax varius', '10/8/1640', 7436756, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into Unicorn (id, name, birthday, color, description) values (49, 'Cynictis penicillata', '7/26/0183', 14697271, 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into Unicorn (id, name, birthday, color, description) values (50, 'Ceratotherium simum', '2/15/0931', 4243933, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
